[defaults]
process_icon = ""
process_colour = "#8caaee"

[shell_override]
enabled = true
shell_name = "zsh"
icon = ""
colour = "#e5c890"

[directories.google]
path = "/google/src/cloud/"
icon = ""
colour = "#ea999c"
extract_tab_name = "^/google/src/cloud/[^/]+/([^/]+)/google$"

[[process]]
names = ["zsh"]
icon = ""

[[process]]
names = ["nvim"]
icon = ""
colour = "#81c8be"

[[process]]
names = ["cargo", "rustc"]
icon = ""

[[process]]
names = ["apt"]
icon = ""

[[process]]
names = ["brew"]
icon = ""

[[process]]
names = ["docker"]
icon = ""

[[process]]
names = ["go"]
icon = ""

[[process]]
names = ["node"]
icon = ""

[[process]]
names = ["tmux"]
icon = ""

[[process]]
names = ["top", "btop"]
icon = ""

[[process]]
names = ["gcc", "clang"]
icon = ""

[[process]]
names = ["make", "cmake"]
icon = ""

[[process]]
names = ["pip", "pip3", "python", "python3"]
icon = ""

[[process]]
names = ["jj"]
icon = ""