[config]
default-process-icon = ""
default-process-colour = "#8caaee"

default-icon = ""
default-icon-colour = "#e5c890"

override-base-shell-name = "zsh"

[[process]]
names = ["zsh"]
icon = ""

[[process]]
names = ["nvim"]
icon = ""
colour = "#81c8be"

[[process]]
names = ["cargo", "rustc"]
icon = ""

[[process]]
names = ["apt"]
icon = ""

[[process]]
names = ["brew"]
icon = ""

[[process]]
names = ["docker"]
icon = ""

[[process]]
names = ["go"]
icon = ""

[[process]]
names = ["node"]
icon = ""

[[process]]
names = ["tmux"]
icon = ""

[[process]]
names = ["top", "btop"]
icon = ""

[[process]]
names = ["gcc", "clang"]
icon = ""

[[process]]
names = ["make", "cmake"]
icon = ""

[[process]]
names = ["pip", "pip3", "python", "python3"]
icon = ""

[[process]]
names = ["jj"]
icon = ""

[directories.google]
path = "/Users/zv/google/src/cloud/slyo/agsa/google"
icon = ""
colour = "#ea999c"