theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[keys.insert]
k = {j = "normal_mode"}